# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build front-end
    - name: Build front-end
      run: |
        docker info
        cd $GITHUB_WORKSPACE
        ls -al
        docker run --volume="$PWD:/usr/src/app" -w /usr/src/app -it node:14.7.0-alpine /bin/sh -c "cd client && npm install && npm run build && cp -r build/* ../server/public"
    
    # Build image
    - name: Build image
      run: |
        docker info
        docker build -t nodeapp -f Dockerfile .

    # Deploy the image
    - shell: bash
      env: 
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
        HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      name: Deploy the image
      run: |         
        docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
        docker tag nodeapp registry.heroku.com/$HEROKU_APP_NAME/web
        docker push registry.heroku.com/$HEROKU_APP_NAME/web                
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:release web -a $HEROKU_APP_NAME
